// Neo4j snapshot of the supplier graph — restore with:
//   docker compose exec -T neo4j cypher-shell -u neo4j -p supplierrisk < backend/data/neo4j_export.cypher
MATCH (n) DETACH DELETE n;
CREATE (:Buyer {name: 'Aurora Medical'});
CREATE (:Buyer {name: 'Cobalt Robotics'});
CREATE (:Buyer {name: 'Helio Diagnostics'});
CREATE (:Buyer {name: 'Northwind Devices'});
CREATE (:Parent {jurisdiction: 'Cayman Islands', name: 'Hanwei Holdings'});
CREATE (:Parent {jurisdiction: 'Delaware', name: 'Meridian Capital Partners'});
CREATE (:Parent {jurisdiction: 'Norway', name: 'Nordkap AS'});
CREATE (:Parent {jurisdiction: 'Norway', name: 'Vertex Industrial Group'});
CREATE (:Site {name: 'Guadalajara Park'});
CREATE (:Site {name: 'Hai Phong Zone 4'});
CREATE (:Site {name: 'Katowice Estate'});
CREATE (:Site {name: 'Pune SEZ'});
CREATE (:Site {name: 'Shenzhen Bao\'an'});
CREATE (:Supplier {category: 'wire harness', country: 'Malaysia', name: 'Aureus Polymers', tier: 1, watchlist: true});
CREATE (:Supplier {category: 'packaging', country: 'Poland', name: 'Baltec Precision', tier: 2, watchlist: false});
CREATE (:Supplier {category: 'injection molding', country: 'Vietnam', name: 'Cygnus Circuits', tier: 1, watchlist: false});
CREATE (:Supplier {category: 'PCB assembly', country: 'India', name: 'Delvia Packaging', tier: 1, watchlist: false});
CREATE (:Supplier {category: 'injection molding', country: 'Vietnam', name: 'Elmwood Metals', tier: 2, watchlist: true});
CREATE (:Supplier {category: 'wire harness', country: 'Germany', name: 'Fenmore Plastics', tier: 1, watchlist: false});
CREATE (:Supplier {category: 'sterile consumables', country: 'China', name: 'Grayline Assembly', tier: 1, watchlist: false});
CREATE (:Supplier {category: 'injection molding', country: 'Vietnam', name: 'Hexa Wireworks', tier: 2, watchlist: false});
CREATE (:Supplier {category: 'wire harness', country: 'Malaysia', name: 'Ironvale Stamping', tier: 1, watchlist: true});
CREATE (:Supplier {category: 'sheet metal', country: 'India', name: 'Juniper Sterile', tier: 1, watchlist: false});
CREATE (:Supplier {category: 'sterile consumables', country: 'India', name: 'Kestrel Components', tier: 1, watchlist: false});
CREATE (:Supplier {category: 'sheet metal', country: 'India', name: 'Lumen Molding', tier: 1, watchlist: false});
CREATE (:Supplier {category: 'injection molding', country: 'Vietnam', name: 'Marnix Electronics', tier: 2, watchlist: true});
CREATE (:Supplier {category: 'injection molding', country: 'India', name: 'Norvent Tooling', tier: 2, watchlist: false});
CREATE (:Supplier {category: 'PCB assembly', country: 'Mexico', name: 'Orbis Cartons', tier: 2, watchlist: false});
CREATE (:Supplier {category: 'sterile consumables', country: 'China', name: 'Pyrite Fabrication', tier: 2, watchlist: false});
CREATE (:Supplier {category: 'sterile consumables', country: 'Germany', name: 'Quandel Harness', tier: 2, watchlist: true});
CREATE (:Supplier {category: 'sheet metal', country: 'Vietnam', name: 'Ravello Circuits', tier: 1, watchlist: false});
CREATE (:Supplier {category: 'sterile consumables', country: 'India', name: 'Serrata Devices', tier: 1, watchlist: false});
CREATE (:Supplier {category: 'packaging', country: 'Mexico', name: 'Tolmen Plastics', tier: 2, watchlist: false});
CREATE (:Supplier {category: 'sterile consumables', country: 'India', name: 'Ulmer Sheetworks', tier: 1, watchlist: true});
CREATE (:Supplier {category: 'wire harness', country: 'Mexico', name: 'Vantis Packaging', tier: 1, watchlist: false});
CREATE (:Supplier {category: 'packaging', country: 'Poland', name: 'Westford Boards', tier: 1, watchlist: false});
CREATE (:Supplier {category: 'sheet metal', country: 'Mexico', name: 'Xiora Molding', tier: 1, watchlist: false});
CREATE (:Supplier {category: 'sheet metal', country: 'Mexico', name: 'Yarrow Consumables', tier: 1, watchlist: true});
CREATE (:Supplier {category: 'sterile consumables', country: 'Vietnam', name: 'Zenkai Precision', tier: 2, watchlist: false});
MATCH (a:Supplier {name: 'Aureus Polymers'}), (b:Supplier {name: 'Cygnus Circuits'}) CREATE (a)-[:DEPENDS_ON {component: 'connectors'}]->(b);
MATCH (a:Supplier {name: 'Baltec Precision'}), (b:Supplier {name: 'Delvia Packaging'}) CREATE (a)-[:DEPENDS_ON {component: 'connectors'}]->(b);
MATCH (a:Supplier {name: 'Baltec Precision'}), (b:Supplier {name: 'Lumen Molding'}) CREATE (a)-[:DEPENDS_ON {component: 'PCBs'}]->(b);
MATCH (a:Supplier {name: 'Baltec Precision'}), (b:Supplier {name: 'Tolmen Plastics'}) CREATE (a)-[:DEPENDS_ON {component: 'connectors'}]->(b);
MATCH (a:Supplier {name: 'Cygnus Circuits'}), (b:Supplier {name: 'Baltec Precision'}) CREATE (a)-[:DEPENDS_ON {component: 'film'}]->(b);
MATCH (a:Supplier {name: 'Cygnus Circuits'}), (b:Supplier {name: 'Norvent Tooling'}) CREATE (a)-[:DEPENDS_ON {component: 'connectors'}]->(b);
MATCH (a:Supplier {name: 'Cygnus Circuits'}), (b:Supplier {name: 'Serrata Devices'}) CREATE (a)-[:DEPENDS_ON {component: 'PCBs'}]->(b);
MATCH (a:Supplier {name: 'Delvia Packaging'}), (b:Supplier {name: 'Fenmore Plastics'}) CREATE (a)-[:DEPENDS_ON {component: 'film'}]->(b);
MATCH (a:Supplier {name: 'Elmwood Metals'}), (b:Supplier {name: 'Grayline Assembly'}) CREATE (a)-[:DEPENDS_ON {component: 'connectors'}]->(b);
MATCH (a:Supplier {name: 'Elmwood Metals'}), (b:Supplier {name: 'Xiora Molding'}) CREATE (a)-[:DEPENDS_ON {component: 'resin'}]->(b);
MATCH (a:Supplier {name: 'Elmwood Metals'}), (b:Supplier {name: 'Yarrow Consumables'}) CREATE (a)-[:DEPENDS_ON {component: 'castings'}]->(b);
MATCH (a:Supplier {name: 'Fenmore Plastics'}), (b:Supplier {name: 'Ironvale Stamping'}) CREATE (a)-[:DEPENDS_ON {component: 'PCBs'}]->(b);
MATCH (a:Supplier {name: 'Grayline Assembly'}), (b:Supplier {name: 'Westford Boards'}) CREATE (a)-[:DEPENDS_ON {component: 'resin'}]->(b);
MATCH (a:Supplier {name: 'Hexa Wireworks'}), (b:Supplier {name: 'Marnix Electronics'}) CREATE (a)-[:DEPENDS_ON {component: 'castings'}]->(b);
MATCH (a:Supplier {name: 'Hexa Wireworks'}), (b:Supplier {name: 'Serrata Devices'}) CREATE (a)-[:DEPENDS_ON {component: 'resin'}]->(b);
MATCH (a:Supplier {name: 'Ironvale Stamping'}), (b:Supplier {name: 'Tolmen Plastics'}) CREATE (a)-[:DEPENDS_ON {component: 'castings'}]->(b);
MATCH (a:Supplier {name: 'Ironvale Stamping'}), (b:Supplier {name: 'Yarrow Consumables'}) CREATE (a)-[:DEPENDS_ON {component: 'PCBs'}]->(b);
MATCH (a:Supplier {name: 'Ironvale Stamping'}), (b:Supplier {name: 'Zenkai Precision'}) CREATE (a)-[:DEPENDS_ON {component: 'PCBs'}]->(b);
MATCH (a:Supplier {name: 'Juniper Sterile'}), (b:Supplier {name: 'Tolmen Plastics'}) CREATE (a)-[:DEPENDS_ON {component: 'connectors'}]->(b);
MATCH (a:Supplier {name: 'Kestrel Components'}), (b:Supplier {name: 'Ironvale Stamping'}) CREATE (a)-[:DEPENDS_ON {component: 'resin'}]->(b);
MATCH (a:Supplier {name: 'Kestrel Components'}), (b:Supplier {name: 'Juniper Sterile'}) CREATE (a)-[:DEPENDS_ON {component: 'connectors'}]->(b);
MATCH (a:Supplier {name: 'Lumen Molding'}), (b:Supplier {name: 'Delvia Packaging'}) CREATE (a)-[:DEPENDS_ON {component: 'film'}]->(b);
MATCH (a:Supplier {name: 'Lumen Molding'}), (b:Supplier {name: 'Elmwood Metals'}) CREATE (a)-[:DEPENDS_ON {component: 'resin'}]->(b);
MATCH (a:Supplier {name: 'Lumen Molding'}), (b:Supplier {name: 'Hexa Wireworks'}) CREATE (a)-[:DEPENDS_ON {component: 'connectors'}]->(b);
MATCH (a:Supplier {name: 'Marnix Electronics'}), (b:Supplier {name: 'Aureus Polymers'}) CREATE (a)-[:DEPENDS_ON {component: 'castings'}]->(b);
MATCH (a:Supplier {name: 'Marnix Electronics'}), (b:Supplier {name: 'Delvia Packaging'}) CREATE (a)-[:DEPENDS_ON {component: 'resin'}]->(b);
MATCH (a:Supplier {name: 'Marnix Electronics'}), (b:Supplier {name: 'Ironvale Stamping'}) CREATE (a)-[:DEPENDS_ON {component: 'resin'}]->(b);
MATCH (a:Supplier {name: 'Norvent Tooling'}), (b:Supplier {name: 'Cygnus Circuits'}) CREATE (a)-[:DEPENDS_ON {component: 'PCBs'}]->(b);
MATCH (a:Supplier {name: 'Norvent Tooling'}), (b:Supplier {name: 'Ulmer Sheetworks'}) CREATE (a)-[:DEPENDS_ON {component: 'connectors'}]->(b);
MATCH (a:Supplier {name: 'Orbis Cartons'}), (b:Supplier {name: 'Ironvale Stamping'}) CREATE (a)-[:DEPENDS_ON {component: 'connectors'}]->(b);
MATCH (a:Supplier {name: 'Orbis Cartons'}), (b:Supplier {name: 'Ulmer Sheetworks'}) CREATE (a)-[:DEPENDS_ON {component: 'castings'}]->(b);
MATCH (a:Supplier {name: 'Orbis Cartons'}), (b:Supplier {name: 'Westford Boards'}) CREATE (a)-[:DEPENDS_ON {component: 'castings'}]->(b);
MATCH (a:Supplier {name: 'Pyrite Fabrication'}), (b:Supplier {name: 'Grayline Assembly'}) CREATE (a)-[:DEPENDS_ON {component: 'connectors'}]->(b);
MATCH (a:Supplier {name: 'Pyrite Fabrication'}), (b:Supplier {name: 'Vantis Packaging'}) CREATE (a)-[:DEPENDS_ON {component: 'connectors'}]->(b);
MATCH (a:Supplier {name: 'Quandel Harness'}), (b:Supplier {name: 'Vantis Packaging'}) CREATE (a)-[:DEPENDS_ON {component: 'connectors'}]->(b);
MATCH (a:Supplier {name: 'Quandel Harness'}), (b:Supplier {name: 'Yarrow Consumables'}) CREATE (a)-[:DEPENDS_ON {component: 'resin'}]->(b);
MATCH (a:Supplier {name: 'Quandel Harness'}), (b:Supplier {name: 'Zenkai Precision'}) CREATE (a)-[:DEPENDS_ON {component: 'castings'}]->(b);
MATCH (a:Supplier {name: 'Ravello Circuits'}), (b:Supplier {name: 'Aureus Polymers'}) CREATE (a)-[:DEPENDS_ON {component: 'resin'}]->(b);
MATCH (a:Supplier {name: 'Ravello Circuits'}), (b:Supplier {name: 'Delvia Packaging'}) CREATE (a)-[:DEPENDS_ON {component: 'connectors'}]->(b);
MATCH (a:Supplier {name: 'Ravello Circuits'}), (b:Supplier {name: 'Fenmore Plastics'}) CREATE (a)-[:DEPENDS_ON {component: 'connectors'}]->(b);
MATCH (a:Supplier {name: 'Serrata Devices'}), (b:Supplier {name: 'Lumen Molding'}) CREATE (a)-[:DEPENDS_ON {component: 'film'}]->(b);
MATCH (a:Supplier {name: 'Serrata Devices'}), (b:Supplier {name: 'Xiora Molding'}) CREATE (a)-[:DEPENDS_ON {component: 'resin'}]->(b);
MATCH (a:Supplier {name: 'Serrata Devices'}), (b:Supplier {name: 'Yarrow Consumables'}) CREATE (a)-[:DEPENDS_ON {component: 'resin'}]->(b);
MATCH (a:Supplier {name: 'Tolmen Plastics'}), (b:Supplier {name: 'Delvia Packaging'}) CREATE (a)-[:DEPENDS_ON {component: 'film'}]->(b);
MATCH (a:Supplier {name: 'Tolmen Plastics'}), (b:Supplier {name: 'Hexa Wireworks'}) CREATE (a)-[:DEPENDS_ON {component: 'film'}]->(b);
MATCH (a:Supplier {name: 'Ulmer Sheetworks'}), (b:Supplier {name: 'Fenmore Plastics'}) CREATE (a)-[:DEPENDS_ON {component: 'PCBs'}]->(b);
MATCH (a:Supplier {name: 'Ulmer Sheetworks'}), (b:Supplier {name: 'Hexa Wireworks'}) CREATE (a)-[:DEPENDS_ON {component: 'castings'}]->(b);
MATCH (a:Supplier {name: 'Vantis Packaging'}), (b:Supplier {name: 'Hexa Wireworks'}) CREATE (a)-[:DEPENDS_ON {component: 'connectors'}]->(b);
MATCH (a:Supplier {name: 'Westford Boards'}), (b:Supplier {name: 'Kestrel Components'}) CREATE (a)-[:DEPENDS_ON {component: 'resin'}]->(b);
MATCH (a:Supplier {name: 'Westford Boards'}), (b:Supplier {name: 'Marnix Electronics'}) CREATE (a)-[:DEPENDS_ON {component: 'connectors'}]->(b);
MATCH (a:Supplier {name: 'Xiora Molding'}), (b:Supplier {name: 'Grayline Assembly'}) CREATE (a)-[:DEPENDS_ON {component: 'film'}]->(b);
MATCH (a:Supplier {name: 'Xiora Molding'}), (b:Supplier {name: 'Quandel Harness'}) CREATE (a)-[:DEPENDS_ON {component: 'resin'}]->(b);
MATCH (a:Supplier {name: 'Yarrow Consumables'}), (b:Supplier {name: 'Juniper Sterile'}) CREATE (a)-[:DEPENDS_ON {component: 'castings'}]->(b);
MATCH (a:Supplier {name: 'Yarrow Consumables'}), (b:Supplier {name: 'Pyrite Fabrication'}) CREATE (a)-[:DEPENDS_ON {component: 'film'}]->(b);
MATCH (a:Supplier {name: 'Zenkai Precision'}), (b:Supplier {name: 'Grayline Assembly'}) CREATE (a)-[:DEPENDS_ON {component: 'resin'}]->(b);
MATCH (a:Supplier {name: 'Zenkai Precision'}), (b:Supplier {name: 'Orbis Cartons'}) CREATE (a)-[:DEPENDS_ON {component: 'castings'}]->(b);
MATCH (a:Supplier {name: 'Zenkai Precision'}), (b:Supplier {name: 'Pyrite Fabrication'}) CREATE (a)-[:DEPENDS_ON {component: 'castings'}]->(b);
MATCH (a:Supplier {name: 'Aureus Polymers'}), (b:Site {name: 'Guadalajara Park'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Baltec Precision'}), (b:Site {name: 'Katowice Estate'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Cygnus Circuits'}), (b:Site {name: 'Hai Phong Zone 4'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Delvia Packaging'}), (b:Site {name: 'Hai Phong Zone 4'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Elmwood Metals'}), (b:Site {name: 'Katowice Estate'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Fenmore Plastics'}), (b:Site {name: 'Pune SEZ'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Grayline Assembly'}), (b:Site {name: 'Pune SEZ'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Hexa Wireworks'}), (b:Site {name: 'Katowice Estate'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Ironvale Stamping'}), (b:Site {name: 'Shenzhen Bao\'an'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Juniper Sterile'}), (b:Site {name: 'Katowice Estate'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Kestrel Components'}), (b:Site {name: 'Guadalajara Park'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Lumen Molding'}), (b:Site {name: 'Hai Phong Zone 4'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Marnix Electronics'}), (b:Site {name: 'Hai Phong Zone 4'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Norvent Tooling'}), (b:Site {name: 'Guadalajara Park'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Orbis Cartons'}), (b:Site {name: 'Shenzhen Bao\'an'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Pyrite Fabrication'}), (b:Site {name: 'Katowice Estate'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Quandel Harness'}), (b:Site {name: 'Pune SEZ'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Ravello Circuits'}), (b:Site {name: 'Pune SEZ'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Serrata Devices'}), (b:Site {name: 'Shenzhen Bao\'an'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Tolmen Plastics'}), (b:Site {name: 'Shenzhen Bao\'an'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Ulmer Sheetworks'}), (b:Site {name: 'Guadalajara Park'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Vantis Packaging'}), (b:Site {name: 'Katowice Estate'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Westford Boards'}), (b:Site {name: 'Katowice Estate'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Xiora Molding'}), (b:Site {name: 'Guadalajara Park'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Yarrow Consumables'}), (b:Site {name: 'Shenzhen Bao\'an'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Zenkai Precision'}), (b:Site {name: 'Pune SEZ'}) CREATE (a)-[:OPERATES_AT]->(b);
MATCH (a:Supplier {name: 'Aureus Polymers'}), (b:Parent {name: 'Meridian Capital Partners'}) CREATE (a)-[:OWNED_BY]->(b);
MATCH (a:Supplier {name: 'Delvia Packaging'}), (b:Parent {name: 'Hanwei Holdings'}) CREATE (a)-[:OWNED_BY]->(b);
MATCH (a:Supplier {name: 'Grayline Assembly'}), (b:Parent {name: 'Vertex Industrial Group'}) CREATE (a)-[:OWNED_BY]->(b);
MATCH (a:Supplier {name: 'Juniper Sterile'}), (b:Parent {name: 'Vertex Industrial Group'}) CREATE (a)-[:OWNED_BY]->(b);
MATCH (a:Supplier {name: 'Marnix Electronics'}), (b:Parent {name: 'Nordkap AS'}) CREATE (a)-[:OWNED_BY]->(b);
MATCH (a:Supplier {name: 'Pyrite Fabrication'}), (b:Parent {name: 'Vertex Industrial Group'}) CREATE (a)-[:OWNED_BY]->(b);
MATCH (a:Supplier {name: 'Serrata Devices'}), (b:Parent {name: 'Meridian Capital Partners'}) CREATE (a)-[:OWNED_BY]->(b);
MATCH (a:Supplier {name: 'Vantis Packaging'}), (b:Parent {name: 'Meridian Capital Partners'}) CREATE (a)-[:OWNED_BY]->(b);
MATCH (a:Supplier {name: 'Yarrow Consumables'}), (b:Parent {name: 'Meridian Capital Partners'}) CREATE (a)-[:OWNED_BY]->(b);
MATCH (a:Supplier {name: 'Aureus Polymers'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Baltec Precision'}), (b:Buyer {name: 'Helio Diagnostics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Baltec Precision'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Cygnus Circuits'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Cygnus Circuits'}), (b:Buyer {name: 'Helio Diagnostics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Cygnus Circuits'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Delvia Packaging'}), (b:Buyer {name: 'Aurora Medical'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Delvia Packaging'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Elmwood Metals'}), (b:Buyer {name: 'Helio Diagnostics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Elmwood Metals'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Fenmore Plastics'}), (b:Buyer {name: 'Aurora Medical'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Fenmore Plastics'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Fenmore Plastics'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Grayline Assembly'}), (b:Buyer {name: 'Helio Diagnostics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Hexa Wireworks'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Hexa Wireworks'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Ironvale Stamping'}), (b:Buyer {name: 'Aurora Medical'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Ironvale Stamping'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Ironvale Stamping'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Juniper Sterile'}), (b:Buyer {name: 'Aurora Medical'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Juniper Sterile'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Juniper Sterile'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Kestrel Components'}), (b:Buyer {name: 'Aurora Medical'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Kestrel Components'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Lumen Molding'}), (b:Buyer {name: 'Aurora Medical'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Lumen Molding'}), (b:Buyer {name: 'Helio Diagnostics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Lumen Molding'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Marnix Electronics'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Marnix Electronics'}), (b:Buyer {name: 'Helio Diagnostics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Marnix Electronics'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Norvent Tooling'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Norvent Tooling'}), (b:Buyer {name: 'Helio Diagnostics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Norvent Tooling'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Orbis Cartons'}), (b:Buyer {name: 'Aurora Medical'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Orbis Cartons'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Orbis Cartons'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Pyrite Fabrication'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Pyrite Fabrication'}), (b:Buyer {name: 'Helio Diagnostics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Quandel Harness'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Quandel Harness'}), (b:Buyer {name: 'Helio Diagnostics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Ravello Circuits'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Ravello Circuits'}), (b:Buyer {name: 'Helio Diagnostics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Serrata Devices'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Tolmen Plastics'}), (b:Buyer {name: 'Aurora Medical'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Tolmen Plastics'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Ulmer Sheetworks'}), (b:Buyer {name: 'Aurora Medical'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Ulmer Sheetworks'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Ulmer Sheetworks'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Vantis Packaging'}), (b:Buyer {name: 'Aurora Medical'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Vantis Packaging'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Vantis Packaging'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Westford Boards'}), (b:Buyer {name: 'Helio Diagnostics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Westford Boards'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Xiora Molding'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Xiora Molding'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Yarrow Consumables'}), (b:Buyer {name: 'Aurora Medical'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Yarrow Consumables'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Zenkai Precision'}), (b:Buyer {name: 'Cobalt Robotics'}) CREATE (a)-[:SUPPLIES_TO]->(b);
MATCH (a:Supplier {name: 'Zenkai Precision'}), (b:Buyer {name: 'Northwind Devices'}) CREATE (a)-[:SUPPLIES_TO]->(b);
